import {config} from "@fortawesome/fontawesome-svg-core";
import {Inter} from "next/font/google";
import Footer from "@/components/Footer";


config.autoAddCss = false;

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "CLOCK[ing]",
    description: "Generated by create next app",
};

export default function AccountLayout({children}) {

    return (
        <section>
        <main className={'min-h-svh'}>
            {children}
        </main>
        <Footer/>
        </section>
    );
}